data:
  train_files: /workspace/user/data/vqa_rad/vqa_rad_train_qwen3_easyr1.jsonl
  val_files: /workspace/user/data/vqa_rad/vqa_rad_test_qwen3_easyr1.jsonl
  prompt_key: prompt
  answer_key: answer
  image_key: images
  video_key: videos
  image_dir: /workspace/user/data/vqa_rad
  video_fps: 2.0
  max_prompt_length: 2048
  max_response_length: 1024
  rollout_batch_size: 128
  mini_rollout_batch_size: null
  val_batch_size: 256
  format_prompt: /workspace/user/utils/format_prompt/vqa.jinja
  override_chat_template: null
  shuffle: true
  seed: 42
  min_pixels: 262144
  max_pixels: 4194304
  filter_overlong_prompts: true

algorithm:
  adv_estimator: grpo
  disable_kl: false
  use_kl_loss: true
  kl_penalty: low_var_kl
  kl_coef: 5.0e-3
  online_filtering: false
  filter_key: overall
  filter_low: 0.01
  filter_high: 0.99

worker:
  actor:
    global_batch_size: 4
    micro_batch_size_per_device_for_update: 1
    micro_batch_size_per_device_for_experience: 2
    max_grad_norm: 1.0
    padding_free: true
    dynamic_batching: true
    ulysses_size: 1
    model:
      model_path: Qwen/Qwen2.5-VL-3B-Instruct
      enable_gradient_checkpointing: true
      trust_remote_code: true
      freeze_vision_tower: true  # Freeze the vision tower
    optim:
      lr: 2.0e-6
      weight_decay: 1.0e-2
      strategy: adamw
      lr_warmup_ratio: 0.03
    fsdp:
      enable_full_shard: true
      enable_cpu_offload: false
      enable_rank0_init: true
    offload:
      offload_params: true
      offload_optimizer: true

  rollout:
    n: 4
    temperature: 1.0
    top_p: 1.0
    limit_images: 0
    gpu_memory_utilization: 0.6
    enforce_eager: false
    enable_chunked_prefill: false
    tensor_parallel_size: 1
    disable_tqdm: false
    val_override_config:
      temperature: 0.6
      top_p: 0.95
      n: 1

  ref:
    fsdp:
      enable_full_shard: true
      enable_cpu_offload: true
      enable_rank0_init: true
    offload:
      offload_params: false

  reward:
    reward_type: batch
    reward_function: /workspace/user/utils/reward_function/vqa_reward.py:compute_score

trainer:
  total_epochs: 10
  max_steps: null
  project_name: VQA-RAD-CoT-QwenVL
  experiment_name: qwen2_5vl_cot_vqa_rad_v1
  logger: ["console", "wandb"]
  nnodes: 1
  n_gpus_per_node: 1
  max_try_make_batch: 20
  val_freq: 0              # ğŸ”¹ æ°¸ä¸è§¦å‘éªŒè¯
  val_before_train: false  # ğŸ”¹ è®­ç»ƒå‰ä¸åšéªŒè¯
  val_only: false          # ğŸ”¹ ç¡®ä¿ä¸æ˜¯â€œåªéªŒè¯æ¨¡å¼â€
  save_freq: 2
  save_limit: 3
  save_model_only: false
  save_checkpoint_path: /workspace/user/checkpoints/VQA-RAD-CoT-QwenVL/qwen2_5vl_cot_vqa_rad_v1
  load_checkpoint_path: null
  find_last_checkpoint: true
